### ISSUE TITLE
files hosted on fedorahosted.org

### ISSUE THREAD

**Issue by omikhailovskii** [Dlackware/gnome-systemd#11]
Resolving fedorahosted.org (fedorahosted.org)... 140.211.169.199
Connecting to fedorahosted.org (fedorahosted.org)|140.211.169.199|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://fedoraproject.org/wiki/Infrastructure/Fedorahosted-retirement

fedorahosted.org was retired on March 1st, 2017.

**Comment by bartgymnast** [comment]
this should affect some downloads indeed.
I will have a look to solve this issue.
Have you been able to get the new download locations yourself ?

**Comment by omikhailovskii** [comment]
yes, it was three archives (pam-redhat-0.99.11.tar.bz2, libpwquality-1.3.0.tar.bz2, pam_krb5-2.4.13.tar.gz) and I just downloaded them from other sources.

**Comment by bartgymnast** [comment]
Issue should now be fixed
