### ISSUE TITLE
update-mime-database is very slow

### ISSUE THREAD

**Issue by montagdude** [Dlackware/gnome-systemd#13]
update-mime-database is holding up the boot process, taking over 40 seconds on my system. I found that the official Slackbuild disables fdatasync, making it many times faster. I recommend doing the same in Dlackware. A patch is attached. (Note: this patch was created on the 3.22/14.2 branch, not master, but it is a very simple change.)
[disable_fdatasync.patch.txt](https://github.com/Dlackware/gnome/files/1199117/disable_fdatasync.patch.txt)

**Comment by belka-ew** [comment]
I created a pull request #14 to get feedback. When it is in the master, I'll merge the changes into 3.22/14.2 as well.
Thanks!
