### ISSUE TITLE
Obsolete DOWNLOAD url in systemd/rebuilds/mesa/mesa.info

### ISSUE THREAD

**Issue by slacky90** [Dlackware/gnome-systemd#16]
Compilation breaks down due to unexistant url in DOWNLOAD variable for branch 3.22/14.2. Should be changed to ftp://ftp.freedesktop.org/pub/mesa/older-versions/11.x/11.2.2/mesa-11.2.2.tar.xz

**Comment by belka-ew** [comment]
Thanks. For know you can download the package, build it manually (with mesa.SlackBuild), remove all packages before gtk+3 from rebuilds/compile-order and restart `dlackware build`.
I'll fix it in the next days.

**Comment by bartgymnast** [comment]
fixed with commit
