### ISSUE TITLE
pylint dependencies missing

### ISSUE THREAD

**Issue by belka-ew** [Dlackware/gnome-systemd#17]
Our pylint builds are broken:

```
$ pip3 check
pylint 1.6.4 requires astroid, which is not installed.
pylint 1.6.4 requires six, which is not installed.
pylint 1.6.4 requires isort, which is not installed.
pylint 1.6.4 requires mccabe, which is not installed.
```

It is the output from 3.22, but it will be similar on master.
Instead of shipping all dependencies separately it would probably make sense to pack them into a single package and maybe rename the target package.

**Comment by bartgymnast** [comment]
pylint is required during compiling totem.
If someone needs the fully function package, they will need to install the above packages

**Comment by belka-ew** [comment]
imho it is still nice if the packages installed by dlackware aren't broken. Is there any way to disable pylint check?
