### ISSUE TITLE
3.22/14.2 cracklib path

### ISSUE THREAD

**Issue by LiohMoeller** [Dlackware/gnome-systemd#21]
cracklib 2.9.6 has been moved to archive:

https://github.com/cracklib/cracklib/archive/v2.9.6.zip

so download of:

https://github.com/cracklib/cracklib/releases/download/cracklib-2.9.6/cracklib-2.9.6.tar.gz

fails.

**Comment by LiohMoeller** [comment]
cracklib-words 2.9.6 has also been removed, so perhaps better bump to 2.7.

Shadow is 4.6 now in current:
ftp://ftp.slackware.com/pub/slackware/slackware-current/source/a/shadow/shadow-4.6.tar.xz

**Comment by bartgymnast** [comment]
the download link is something that can be fixed.
the shadow package update is something not for the 3.22/14.2 release.
Shadow 4.6 (not in slack 14.2, but in 15.0) can be found in newer versions though.
Master git needs a few more updates and is 3.32 on -current/15.0 (and has shadow 4.6)

**Comment by franksawar** [comment]
Hiya Guys,

I would like to know which file I have to patch?, or to which specific folder I have to download cracklib?

**Comment by belka-ew** [comment]
https://github.com/Dlackware/pam/blob/master/cracklib/cracklib.info

But the download links in master work as expected.
