### ISSUE TITLE
some issuses to build dlackwar on Slackware current

### ISSUE THREAD

**Issue by slackernetuk** [Dlackware/gnome-systemd#22]
Hiya, 

I've tried to build dlackware 3.34/current-20191013 on a fresh installed Slackware current x86_64.

1. compile-order wasn't found in dlackware/gnome/systemd/systemd
    my solution ln -sf /usr/src/dlackware/gnome/systemd/compile-order 
                               /usr/src/dlackware/gnome/systemd/systemd/

2. when I've built pam-krb5 .... wayland wasn't found
    how I can fix that?

3. It would be great to have a continue flag in dlackware build script?

**Comment by belka-ew** [comment]
Please try master. It is also 3.34 for slackware current. I've built it recently and only a few gnome/apps don't build yet but I'm working on updating them (Gnome Desktop works in my VM). I'm not sure what is the state of dlackware 3.34/current-20191013.

Also use the build system from master. It seems we will switch to it for Slackware 15. The old one may be incompatible with the latest changes. The new one also checks what packages are installed and continues building automatically.

And I see that the documentation for building on current is out of sync. Will update it in the next two weeks.

If you have any difficulties or questions when building from master, please let me know; it would be of great help.

**Comment by slackernetuk** [comment]
@belka-ew 
I guess I've tones of questions. :rofl: 

Ok, I've switched to master and had exactly the same issue.

```
`git checkout master
M	systemd
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
git submodule update --init
Submodule path 'systemd': checked out
'2ea96506b51ad0dd49f00a11485d2073f13c034a'

Package pam-krb5-4.8-x86_64-2_dlack.txz installed.
Package pam-krb5-4.8-x86_64-2_dlack upgraded with new package
/var/cache/dlackware/pam-krb5-4.8-x86_64-2_dlack.txz.
wayland wasn't found.`
```

Just a guess, but it seems like a script problem.
My workaround was to install systemd & deps manually.

The next issue was to install core, because there is no
`systemd/rebuilds/compile-order base/compile-order apps/compile-order`
but 
`apps  core  extra  pam  screenshot sysdeps  systemd`

`DLACK_REPOS=`sysdeps/compile-order core/compile-order``

Is my $DLACK_REPOS correct? I'm not bothered about apps & extras, I can install these things later.

thanks a lot :+1:

**Comment by belka-ew** [comment]
It seems you still use the old build system.

0. Probably remove the old one (should be `removepkg dlackware`).
1. Install Stack as root (it is a single binary, will be probably downloaded into `/usr/local/bin` or `~/.local/bin`): 
`wget -qO- https://get.haskellstack.org/ | sh`
2. Get the master from https://github.com/Dlackware/dlackware. Go into the cloned "dlackware" directory. Copy etc/dlackware.yaml.new to etc/dlackware.yaml and you can adjust `reposRoot` there.
3. And then as root:
```
stack build
stack exec dlackware -- build
```

**Comment by belka-ew** [comment]
@slackernetuk any success here?
