### ISSUE TITLE
Nautilus crashed

### ISSUE THREAD

**Issue by slackernetuk** [Dlackware/gnome-systemd#24]
Hiya,

recently I've built Gnome 3.34.0 on Slackware current, everything works quite well, but nautilus crashed. Can you give some recommendations to solve it? 

BTW
`glib-compile-schemas /usr/share/glib-2.0/schemas` didn't help.

thanks 

```
(org.gnome.Nautilus:81301): WARNING **: 11:15:53.998: Error on getting connection: Failed to load SPARQL backend: GDBus.Error:org.freedesktop.systemd1.NoSuchUnit: Unit tracker-store.service not found.

(org.gnome.Nautilus:81301): GLib-GIO-ERROR **: 11:15:54.053: Settings schema 'org.freedesktop.Tracker.Miner.Files' is not installed
Trace/breakpoint trap (core dumped)
```

**Comment by slackernetuk** [comment]
Nautilus needs more dependencies libgrss & tracker-mines.

**Comment by belka-ew** [comment]
Ah, I thought it would be something like this, missing .service files and schemas. Thanks for tracking that down.

**Comment by belka-ew** [comment]
Fixed user service installation path in tracker and added tracker-miners (with disabled libgrss).
