### ISSUE TITLE
Glib2

### ISSUE THREAD

**Issue by slackernetuk** [Dlackware/gnome-systemd#25]
glib2 isn't up to date, I had some version conflicts with several packages. At the moment I'm testing with glib-2.63.6.

[glib2.diff.txt](https://github.com/Dlackware/gnome/files/4491835/glib2.diff.txt)

**Comment by belka-ew** [comment]
I think we can leave out glib2 and use the slackware's stock package, it is 2.64.2 for now.
This weekend I'll push an update and remove some packages. gtk+3, glib2, glib-networking, mesa, xorg-server, xorg-server-wayland, openssh shouldn't be needed anymore and I could build 3.36 without them. I'd like to do just one test more and try to skip a few more packages.
My current (master) build is unfortunately not working; I'm trying to replace our PAM and wayland with slackware's versions and it still needs some work.

**Comment by belka-ew** [comment]
![Bildschirmfoto von 2020-04-19 12-12-29](https://user-images.githubusercontent.com/8720597/79689242-b8a5ee00-8253-11ea-8fcd-f439061e3db1.png)

Our PAM is slightly broken. Slackware renamed/removed/changed some PAM modules, so the references in our PAM modules are partly invalid.

I rewrote systemd and gdm PAM configuration and next week I'm going to push these updates and a few updated packages I have locally.
