### ISSUE TITLE
[pango] systemd service failure

### ISSUE THREAD

**Issue by belka-ew** [Dlackware/gnome-systemd#6]
```
Failed to start Run update-pango-querymodules
```

**Comment by bartgymnast** [comment]
Did you install the systemd-service-files ?

**Comment by belka-ew** [comment]
Yes, I think it was installed.

**Comment by bartgymnast** [comment]
pango actually does not use it, I removed the update-pango-querymodules service file.
Just need an extra verification that it is not used or valid service file
