### ISSUE TITLE
gnome-terminal icon is missing

### ISSUE THREAD

**Issue by belka-ew** [Dlackware/gnome-systemd#7]
gnome terminal icon is shown only in the activities-menu but not in the left sidebar and not on the top bar then the terminal was started

**Comment by bartgymnast** [comment]
LC_ALL needs to be utf8
On 26 Jan 2016 14:29, Eugene Wissner notifications@github.com wrote:gnome terminal icon is shown only in the activities-menu but not in the left sidebar and not on the top bar then the terminal was started

**Comment by belka-ew** [comment]
I don't think it is the problem. I have the locale set and gnome-terminal starts, but wrong icons are shown.

**Comment by belka-ew** [comment]
![bildschirmfoto von 2016-01-27 00-59-40](https://cloud.githubusercontent.com/assets/8720597/12599400/d630703c-c491-11e5-941a-2e2643ab7819.png)
![bildschirmfoto von 2016-01-27 01-02-43](https://cloud.githubusercontent.com/assets/8720597/12599401/d63c3732-c491-11e5-80aa-8f48cd095af6.png)
