### ISSUE TITLE
empathy to /extra

### ISSUE THREAD

**Issue by bartgymnast** [Dlackware/gnome-systemd#8]
looking into moving empathy into the extra directory together with the telepathy libs

**Comment by belka-ew** [comment]
I will exclude it from compile order and try to build gnome without telepathy.
Actually pidgin doesn't integrate nicely with gnome (no notifications). There was a plugin for gnome shell but I haven't tested it yet.

**Comment by belka-ew** [comment]
Telepathy is used by other gnome applications like Online Accounts. Telepathy farstream can be safely removed however
